### ISSUE TITLE
Invalidate a match based on strict equality of a column

### ISSUE THREAD

**Issue by ian-manaog** [moj-analytical-services/splink#434]
How do we deal with strict rules/requirements? For example, mismatching middle names should not be found in matches/linked groups.

An example scenario:
Let us say we have two individuals, John A. Smith, and John B. Smith, and the information I have on hand to compare is address and profession. Profession and Address are matching and any other fields are missing. From that alone, Splink should give this match a high **match_probability**. Now, if we have requirements or rules which state that in no circumstances should individuals with mismatching middle names be grouped together, this match should be invalidated even if the resulting match_probability says otherwise.

So far I've tried blocking rules and using sql_gen_case_smnt_strict_equality_2 (w/c I found in case_statements.py). These didn't give the result I require. As a last resort, I'm thinking of attempting to just modify the dataframe which contains the match scores (**df_e** in the demos), wherein I look for pairs with mismatching middle names and explicitly set the match_probability as 0.

**Comment by samnlindsay** [comment]
You've almost done it by using `sql_gen_case_smnt_strict_equality_2`. The missing step is to specify the m-probabilities for the column you want a strict rule on, and to hold these m-probabilities fixed. For your example scenario with a column called `middle_name` that must match, your `settings["comparison_columns"]` should include something like the following:

```
    {
        "col_name": "middle_name",
        "m_probabilities": [1e-9, 1.], 
        "fix_m_probabilities": True
    },
```

The default `num_levels` is 2 and the default case expression is `sql_gen_case_smnt_strict_equality_2` so they don't need to be specified. Among matches, the m-probability of a match on middle name is set to 1, and of a non-match (effectively) zero. These probabilities are fixed so the EM algorithm will not update them.

Note that I have used 1e-9 as zero probabilities can be problematic in the final match weight calculations.

**Comment by ian-manaog** [comment]
Thanks for the quick reply!

Apologies, I forgot to mention I also tried fixed probabilities before, it wasn't completely effective. Although I haven't tried 1e-9, the closest number to zero I used was 0.001. 

I mentioned using fixed probabilities **wasn't completely effective** as there are cases where pairs with mismatching middle names would still match up and group together. Upon inspecting charts, specifically the `bayes_factor_intuition_chart`, I noticed that with enough matching columns, the mismatched middle name score/gamma would get overridden by other columns' score/gamma. Especially if the middle name alone mismatches and everything else, if present, matches. 

I'll try your suggestion of using **1e-9** to represent zero and see if it changes the results. I'll also prepare to show samples of the `bayes_factor_intuition_chart` if I see the same cases as before. Thanks again for your help.

**Comment by samnlindsay** [comment]
0.001 corresponds to a match weight/log2 bayes factor of just -10 so if several other fields match, it would not be surprising if the match probability ends up quite high. 

1e-9 gives a match weight of -30 which should be much more robust to such cases, but you can go arbitrarily small to make sure. I hope that solves it for you 🤞

**Comment by ian-manaog** [comment]
The suggestion of using **1e-9** works great. I have significantly fewer cases where middle names mismatch yet the match score is high. I still have a few cases but I think making the zero representation for m-probabilities smaller would help.

Thanks again for the help 😄
